'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Alerts
    
    '''<summary>
    '''upAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upAlert As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''gvDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDocs As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblVesselName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVesselName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvCrewDocEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCrewDocEx As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvOffSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOffSign As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblVesselName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVesselName2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gvCrewSignoff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCrewSignoff As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hdnVesselCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVesselCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnVesselName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVesselName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnCrewNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCrewNo As Global.System.Web.UI.WebControls.HiddenField
End Class
