'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasterPage
    
    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''ProfileImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProfileImage As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblProfileName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfileName2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProfile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProfile2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblLogout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogout1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Rec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rec As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Recs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Recs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recs2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RecAF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecAF As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Alert As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AlertAl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertAl As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AlertCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertCP As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AlertCPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertCPs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Home control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''HomeCr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeCr As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''HomeVe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeVe As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Acc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Acc As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Accs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Accs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Accs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Accs2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AccUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccUM As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AccUMs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccUMs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AccMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccMP As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AccMPs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccMPs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''VW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VW As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''VWMV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VWMV As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''VWMW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VWMW As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Pay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Pay1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pay1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Pay2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pay2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pPay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Reports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reports As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Reports1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reports1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Reports2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reports2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ReportsR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportsR As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Sett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sett As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Setts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Setts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Setts2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Setts2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettDR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettDR As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettDRs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettDRs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettTC As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettTCs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettTCs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettRa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettRa As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettRas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettRas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettRea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettRea As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettReas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettReas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettVC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettVC As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SettVC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SettVC1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
