'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WagesArchive
    
    '''<summary>
    '''upGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upGrid As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnAddNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNew As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblddlPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblddlPrincipal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrincipal As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblRankS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRankS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlRankS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRankS As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnGo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGo1 As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vViewKewords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vViewKewords As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''gvWage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvWage As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvWageP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvWageP As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''vUpdateKeywords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vUpdateKeywords As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lblHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlPrincipalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrincipalCode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRank As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlScale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScale As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtBasicWage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBasicWage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWorkHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWorkHours As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOTPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOTPay As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOTRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOTRate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLeavePay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLeavePay As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWeekendPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeekendPay As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSocialBonus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSocialBonus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllowance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDndAllowance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDndAllowance As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtIMO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbBack As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnAddUpdateWages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddUpdateWages As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''vAddNewKeywords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddNewKeywords As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''hdnMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnView As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''vActionNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vActionNotification As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnBack2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack2 As Global.System.Web.UI.WebControls.Button
End Class
